/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#bdcac1",
        "on-tertiary-fixed": "#131e19",
        "on-tertiary-container": "#7a877f",
        "tertiary-container": "#131e19",
        "on-error-container": "#93000a",
        "surface-variant": "#d3e4fe",
        "on-background": "#0b1c30",
        "tertiary": "#000000",
        "surface": "#f8f9ff",
        "on-error": "#ffffff",
        "surface-tint": "#565e74",
        "primary": "#000000",
        "surface-container-high": "#dce9ff",
        "primary-container": "#131b2e",
        "outline-variant": "#c6c6cd",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed": "#131b2e",
        "surface-container-low": "#eff4ff",
        "on-secondary": "#ffffff",
        "on-surface": "#0b1c30",
        "background": "#f8f9ff",
        "secondary-fixed": "#6ffbbe",
        "secondary": "#006c49",
        "inverse-primary": "#bec6e0",
        "inverse-surface": "#213145",
        "surface-dim": "#cbdbf5",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed-variant": "#3f465c",
        "tertiary-fixed": "#d9e6dd",
        "primary-fixed": "#dae2fd",
        "surface-container": "#e5eeff",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#4edea3",
        "outline": "#76777d",
        "error-container": "#ffdad6",
        "on-secondary-container": "#00714d",
        "error": "#ba1a1a",
        "inverse-on-surface": "#eaf1ff",
        "secondary-container": "#6cf8bb",
        "on-secondary-fixed": "#002113",
        "on-primary-container": "#7c839b",
        "on-surface-variant": "#45464d",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#3e4943"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin": "32px",
        "xs": "8px",
        "xl": "64px",
        "md": "24px",
        "base": "4px",
        "lg": "40px",
        "sm": "16px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "h2": ["Manrope", "sans-serif"],
        "h1": ["Manrope", "sans-serif"],
        "display": ["Manrope", "sans-serif"],
        "h3": ["Manrope", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "h2": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "h1": ["32px", { "lineHeight": "1.25", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "h3": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.04em", "fontWeight": "500" }]
      },
    },
  },
  plugins: [],
}
